title: The X-Files Research Institute
author:
  name: Muqiu Han
  email: muqiu-han@outlook.com

description: >
  An organization that studies any paranormal phenomenon in the world, and this is its offshoot, a purely open source organization that aims to explore the fields of computer science and open source.

theme: minimal