// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.js";
import * as Styles from "../Styles.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import CardPng from "../assets/card.png";

var card_image = CardPng;

function Blogs(props) {
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("h3", {
                              children: [
                                "将你热爱的事物传递下去，",
                                JsxRuntime.jsx("br", {
                                      className: "sm:block hidden"
                                    }),
                                "或传递给未来的自己。"
                              ],
                              className: Styles.styles.heading3
                            }),
                        JsxRuntime.jsx("p", {
                              children: "一个技术博客可以帮助许多人学习和成长，就像你个人的成长一样。",
                              className: Styles.styles.paragraph + " mt-5"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "毕竟，当我们尝试学习新东西时，也会去寻找博客。",
                              className: Styles.styles.paragraph + " mt-5"
                            }),
                        JsxRuntime.jsx(Button.make, {
                              styles: "mt-10"
                            })
                      ],
                      className: Styles.layout.sectionInfo
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            className: "w-[100%] h-[100%]",
                            alt: "billing",
                            src: card_image
                          }),
                      className: Styles.layout.sectionImg
                    })
              ],
              className: Styles.layout.section
            });
}

var make = Blogs;

export {
  card_image ,
  make ,
}
/* card_image Not a pure module */
