// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  return JsxRuntime.jsx("span", {
              children: JsxRuntime.jsx("button", {
                    children: "加入我们",
                    className: "py-4 px-6 font-poppins font-medium text-[18px] text-[#f6f6f6] bg-blue-gradient rounded-[10px] outline-none hover:opacity-80"
                  }),
              className: props.styles
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
