// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as Constants from "../Constants.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function CTA(props) {
  return JsxRuntime.jsx("section", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h2", {
                            children: "Let's try our service now!",
                            className: Styles.styles.heading2
                          }),
                      JsxRuntime.jsx("p", {
                            children: "Everything you need to accept card payments and grow your business\n        anywhere on the planet.",
                            className: Styles.styles.paragraph + " max-w-[470px] mt-5"
                          }),
                      JsxRuntime.jsx("section", {
                            children: JsxRuntime.jsx("div", {
                                  children: Constants.clients.map(function (client) {
                                        return JsxRuntime.jsx("div", {
                                                    children: JsxRuntime.jsx("img", {
                                                          className: "sm:w-[20%] w-[50%] object-contain",
                                                          alt: "client_logo",
                                                          src: client.logo
                                                        }),
                                                    className: "flex-1 " + Styles.styles.flexCenter + " sm:min-w-[20%] min-w-[20%] mt-5"
                                                  }, client.id);
                                      }),
                                  className: Styles.styles.flexCenter + " flex-wrap w-full"
                                }),
                            className: Styles.styles.flexCenter + " my-4"
                          })
                    ],
                    className: "flex-1 flex flex-col"
                  }),
              className: Styles.styles.flexCenter + " " + Styles.styles.marginY + " " + Styles.styles.padding + " sm:flex-row flex-col bg-black-gradient-2 rounded-[20px] box-shadow"
            });
}

var make = CTA;

export {
  make ,
}
/* Styles Not a pure module */
