// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import LogoPng from "/logo.png";
import * as Constants from "../Constants.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Footer(props) {
  var social_mb = function (index) {
    if (index !== (Constants.socialMedia.length - 1 | 0)) {
      return "mr-6";
    } else {
      return "mr-0";
    }
  };
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("img", {
                                    className: "w-[266px] h-[72.14px] object-contain",
                                    alt: "hoobank",
                                    src: LogoPng
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "一个纯粹的开源组织，旨在探索计算机科学和开源领域。",
                                    className: Styles.styles.paragraph + " mt-4"
                                  })
                            ],
                            className: "flex-[1] flex flex-col justify-center items-center"
                          }),
                      className: Styles.styles.flexStart + " md:flex-row flex-col mb-8 w-full"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                              children: "Copyright Ⓒ 2024 The X-Files Research Institute. All Rights Reserved.",
                              className: "font-poppins font-normal text-center text-[18px] leading-[27px] text-white"
                            }),
                        JsxRuntime.jsx("div", {
                              children: Constants.socialMedia.map(function (social, index) {
                                    return JsxRuntime.jsx("img", {
                                                className: social_mb(index) + " w-[21px] h-[21px] object-contain cursor-pointer",
                                                alt: social.id,
                                                src: social.icon,
                                                onClick: (function (_event) {
                                                    document.location.href = social.link;
                                                  })
                                              }, social.id);
                                  }),
                              className: "flex flex-row md:mt-0 mt-6"
                            })
                      ],
                      className: "w-full flex justify-between items-center md:flex-row flex-col pt-6 border-t-[1px] border-t-[#3F3E45]"
                    })
              ],
              className: Styles.styles.flexCenter + " " + Styles.styles.paddingY + " flex-col"
            });
}

var make = Footer;

export {
  make ,
}
/* Styles Not a pure module */
