// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import ArrowUpSvg from "../assets/arrow-up.svg";

var arrow_up_icon = ArrowUpSvg;

function GetStarted(props) {
  return JsxRuntime.jsx("a", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("p", {
                                          children: JsxRuntime.jsx("span", {
                                                children: "立即",
                                                className: "text-[#8ca7d8]"
                                              }),
                                          className: "font-poppins font-medium mr-2 text-[18px] leading-[23.4px]"
                                        }),
                                    JsxRuntime.jsx("img", {
                                          className: "w-[23px] h-[23px] object-contain",
                                          alt: "arrow-up",
                                          src: arrow_up_icon
                                        })
                                  ],
                                  className: Styles.styles.flexStart + " flex-row"
                                }),
                            JsxRuntime.jsx("p", {
                                  children: JsxRuntime.jsx("span", {
                                        children: "加入我们",
                                        className: "text-[#8ca7d8]"
                                      }),
                                  className: "font-poppins font-medium text-[18px] leading-[23.4px]"
                                })
                          ],
                          className: Styles.styles.flexCenter + " flex-col bg-primary w-[100%] h-[100%] rounded-full"
                        }),
                    className: Styles.styles.flexCenter + " w-[140px] h-[140px] rounded-full bg-blue-gradient p-[2px] cursor-pointer"
                  }),
              href: "https://github.com/x-fri"
            });
}

var make = GetStarted;

export {
  arrow_up_icon ,
  make ,
}
/* arrow_up_icon Not a pure module */
