// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.js";
import * as Styles from "../Styles.bs.js";
import * as Constants from "../Constants.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Highlights$FeatureCard(props) {
  var feature = props.feature;
  var mb = props.index !== (Constants.features.length - 1 | 0) ? "mb-6" : "mb-9";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            className: "w-[50%] h-[50%] object-contain",
                            alt: "icon",
                            src: feature.icon
                          }),
                      className: Styles.styles.flexCenter + " w-[64px] h-[64px] rounded-full bg-dimBlue"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h4", {
                              children: feature.title,
                              className: "font-poppins font-semibold text-white text-[18px] leading-[23px] mb-1"
                            }),
                        JsxRuntime.jsx("p", {
                              children: feature.content,
                              className: "font-poppins font-normal text-dimWhite text-[18px] leading-[23px] mb-1"
                            })
                      ],
                      className: "flex-1 flex flex-col ml-3"
                    })
              ],
              className: mb + " flex flex-row p-6 rounded-[20px] feature-card"
            });
}

var FeatureCard = {
  make: Highlights$FeatureCard
};

function Highlights(props) {
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("h3", {
                              children: [
                                "在与你有相同爱好的人群中，",
                                JsxRuntime.jsx("br", {
                                      className: "sm:block hidden"
                                    }),
                                "进一步寻找你需要的技术栈。"
                              ],
                              className: Styles.styles.heading3
                            }),
                        JsxRuntime.jsx("p", {
                              children: "我们不带偏见地看待各种技术，OCaml、F#、Rescript、C++、Rust、Golang、Scala、Java、Kotlin、Clojure、JavaScript、TypeScript、Python...（排名不分先后）",
                              className: Styles.styles.paragraph + " max-w-[470px] mt-5"
                            }),
                        JsxRuntime.jsx(Button.make, {
                              styles: "mt-10"
                            })
                      ],
                      className: Styles.layout.sectionInfo
                    }),
                JsxRuntime.jsx("div", {
                      children: Constants.features.map(function (feature, index) {
                            return JsxRuntime.jsx(Highlights$FeatureCard, {
                                        feature: feature,
                                        index: index
                                      }, feature.id);
                          }),
                      className: Styles.layout.sectionImg + " flex-col"
                    })
              ],
              className: Styles.layout.section
            });
}

var make = Highlights;

export {
  FeatureCard ,
  make ,
}
/* Button Not a pure module */
