// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as GetStarted from "./GetStarted.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import RobotPng from "../assets/robot.png";
import DiscountSvg from "../assets/Discount.svg";

var discount = DiscountSvg;

var robot_image = RobotPng;

function Home(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsxs("section", {
                        children: [
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx("img", {
                                                className: "w-[32px] h-[32px]",
                                                alt: "discount",
                                                src: discount
                                              }),
                                          JsxRuntime.jsxs("p", {
                                                children: [
                                                  "为一切纯粹的",
                                                  JsxRuntime.jsx("span", {
                                                        children: "热爱",
                                                        className: "text-white"
                                                      }),
                                                  "带来无限的",
                                                  JsxRuntime.jsx("span", {
                                                        children: "活力",
                                                        className: "text-white"
                                                      })
                                                ],
                                                className: Styles.styles.paragraph + " ml-2"
                                              })
                                        ],
                                        className: "flex flex-row items-center py-[6px] px-4 bg-discount-gradient rounded-[10px] mb-2"
                                      }),
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsxs("h1", {
                                                children: [
                                                  "X档案研究所",
                                                  JsxRuntime.jsx("br", {
                                                        className: "sm:block hidden"
                                                      }),
                                                  JsxRuntime.jsx("span", {
                                                        children: "The X-Files Research Institute",
                                                        className: "text-gradient"
                                                      }),
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsx("div", {
                                                                className: "animate-pulse absolute z-[0] w-[15%] h-[15%] rounded-full pink__gradient"
                                                              }),
                                                          JsxRuntime.jsx("div", {
                                                                className: "absolute z-[1] w-[5%] h-[5%] rounded-full white__gradient"
                                                              }),
                                                          JsxRuntime.jsx("div", {
                                                                className: "animate-bounce absolute z-[0] w-[15%] h-[15%] rounded-full blue__gradient"
                                                              })
                                                        ],
                                                        className: "flex-1 flex " + Styles.styles.flexCenter + " md:my-0 my-0 "
                                                      })
                                                ],
                                                className: "flex-1 font-semibold ss:text-[72px] text-[52px] text-white ss:leading-[100.8px] leading-[75px]"
                                              }),
                                          JsxRuntime.jsx("div", {
                                                children: JsxRuntime.jsx(GetStarted.make, {}),
                                                className: "ss:flex hidden md:mr-4 mr-0"
                                              })
                                        ],
                                        className: "flex flex-row justify-between items-center w-full"
                                      }),
                                  JsxRuntime.jsx("p", {
                                        children: "由来自五湖四海，各行各业中拥有相同爱好的人们组成的一个纯粹的开源组织，旨在探索计算机科学和开源领域。",
                                        className: Styles.styles.paragraph + " max-w-[470px] mt-5"
                                      })
                                ],
                                className: "flex-1 " + Styles.styles.flexStart + " flex-col xl:px-0 sm:px-16 px-6"
                              }),
                          JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsx("img", {
                                      className: "w-[100%] h-[100%] relative z-[5]",
                                      alt: "robot_image",
                                      src: robot_image
                                    }),
                                className: "flex-1 flex " + Styles.styles.flexCenter + " md:my-0 my-10 relative"
                              }),
                          JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsx(GetStarted.make, {}),
                                className: "ss:hidden " + Styles.styles.flexCenter
                              })
                        ],
                        className: "flex md:flex-row flex-col " + Styles.styles.paddingY,
                        id: "home"
                      }))
            });
}

var make = Home;

export {
  discount ,
  robot_image ,
  make ,
}
/* discount Not a pure module */
