// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import BillPng from "../assets/bill.png";
import GiteaSvg from "../assets/gitea.svg";
import GithubSvg from "../assets/github.svg";
import CodebergSvg from "../assets/codeberg.svg";
import FramagitSvg from "../assets/framagit.svg";

var bill_image = BillPng;

var framagit_logo = FramagitSvg;

var github_logo = GithubSvg;

var codeberg_logo = CodebergSvg;

var gitea_logo = GiteaSvg;

function Hostings(props) {
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              className: "w-[100%] h-[100%] relative z-[5]",
                              alt: "billing",
                              src: bill_image
                            }),
                        JsxRuntime.jsx("div", {
                              className: "absolute z-[3] -left-1/2 top-0 w-[50%] h-[50%] rounded-full white__gradient"
                            }),
                        JsxRuntime.jsx("div", {
                              className: "absolute z-[0] w-[50%] h-[50%] -left-1/2 bottom-0 rounded-full pink__gradient"
                            })
                      ],
                      className: Styles.layout.sectionImgReverse
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("h2", {
                              children: [
                                "在你喜欢的代码托管平台中",
                                JsxRuntime.jsx("br", {
                                      className: "sm:block hidden"
                                    }),
                                "轻松地管理你的仓库"
                              ],
                              className: Styles.styles.heading2
                            }),
                        JsxRuntime.jsx("p", {
                              children: "这个世界上存在众多不同的版本控制系统（VCS）和代码托管平台（Github，GitLab等）。我们支持众多不同的平台，您可以自由选择它们之中最适合的。",
                              className: Styles.styles.paragraph + " max-w-[470px] mt-5"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      className: "w-[144.17px] h-[43.08px] object-contain cursor-pointer",
                                      alt: "framagit",
                                      src: framagit_logo
                                    }),
                                JsxRuntime.jsx("img", {
                                      className: "w-[128.86px] h-[42.05px] object-contain mr-5 cursor-pointer",
                                      alt: "github",
                                      src: github_logo
                                    }),
                                JsxRuntime.jsx("img", {
                                      className: "w-[144.17px] h-[43.08px] object-contain cursor-pointer",
                                      alt: "codeberg",
                                      src: codeberg_logo
                                    }),
                                JsxRuntime.jsx("img", {
                                      className: "w-[144.17px] h-[43.08px] object-contain cursor-pointer",
                                      alt: "gitea",
                                      src: gitea_logo
                                    })
                              ],
                              className: "flex sm:mt-10 mt-6 py-[6px] px-4 bg-black-gradient rounded-[10px] "
                            })
                      ],
                      className: Styles.layout.sectionInfo
                    })
              ],
              className: Styles.layout.sectionReverse,
              id: "product"
            });
}

var make = Hostings;

export {
  bill_image ,
  framagit_logo ,
  github_logo ,
  codeberg_logo ,
  gitea_logo ,
  make ,
}
/* bill_image Not a pure module */
