// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "../Styles.bs.js";
import * as Constants from "../Constants.bs.js";
import * as FeedbackCard from "./FeedbackCard.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Testimonials(props) {
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("div", {
                      className: "absolute z-[0] w-[60%] h-[60%] blue__gradient bottom-40"
                    }),
                JsxRuntime.jsx("div", {
                      className: "absolute z-[0] w-[60%] h-[60%] -right-[50%] rounded-full blue__gradient bottom-40"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "人们对X档案研究所的看法",
                              className: Styles.styles.heading2
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: "任何事物在人们不同的视角下都会有不同的评价。",
                                      className: Styles.styles.paragraph + " text-left max-w-[450px]"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "毕竟，思想——人的全部尊严就在于思想。",
                                      className: Styles.styles.paragraph + " text-left max-w-[450px]"
                                    })
                              ],
                              className: "w-full md:mt-0 mt-6"
                            })
                      ],
                      className: "w-full flex justify-between items-center md:flex-row flex-col sm:mb-16 mb-6 relative z-[1]"
                    }),
                JsxRuntime.jsx("div", {
                      children: Constants.feedback.map(function (card) {
                            return JsxRuntime.jsx(FeedbackCard.make, {
                                        card: card
                                      }, card.id);
                          }),
                      className: "flex flex-wrap sm:justify-start justify-center w-full feedback-container relative z-[1]"
                    })
              ],
              className: Styles.styles.paddingY + " " + Styles.styles.flexCenter + " flex-col relative ",
              id: "clients"
            });
}

var make = Testimonials;

export {
  make ,
}
/* Styles Not a pure module */
