version = 3.8.1
runner.dialect = scala3
indent.main = 4
maxColumn = 80
newlines.source = unfold

continuationIndent.callSite = 2
continuationIndent.defnSite = 2
danglingParentheses.preset = true
align.openParenCallSite = false
align.openParenDefnSite = false

docstrings.style = keep

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes
rewrite.scala3.removeEndMarkerMaxLines = 0
rewrite.scala3.insertEndMarkerMinLines = 1