// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CTA from "./components/CTA.bs.js";
import * as Home from "./components/Home.bs.js";
import * as Stats from "./components/Stats.bs.js";
import * as Client from "./components/Client.bs.js";
import * as Footer from "./components/Footer.bs.js";
import * as Navbar from "./components/Navbar.bs.js";
import * as Styles from "./Styles.bs.js";
import * as CardDeal from "./components/CardDeal.bs.js";
import * as Hostings from "./components/Hostings.bs.js";
import * as Highlights from "./components/Highlights.bs.js";
import * as Testimonials from "./components/Testimonials.bs.js";
import LogoSvg from "./assets/logo.svg";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(Navbar.make, {}),
                      className: Styles.styles.paddingX + " " + Styles.styles.flexCenter
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx(Home.make, {}),
                            className: Styles.styles.boxWidth
                          }),
                      className: "bg-primary " + Styles.styles.flexStart
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(Stats.make, {}),
                              JsxRuntime.jsx(Highlights.make, {}),
                              JsxRuntime.jsx(Hostings.make, {}),
                              JsxRuntime.jsx(CardDeal.make, {}),
                              JsxRuntime.jsx(Testimonials.make, {}),
                              JsxRuntime.jsx(Client.make, {}),
                              JsxRuntime.jsx(CTA.make, {}),
                              JsxRuntime.jsx(Footer.make, {})
                            ],
                            className: Styles.styles.boxWidth
                          }),
                      className: "bg-primary " + Styles.styles.paddingX + " " + Styles.styles.flexStart
                    })
              ],
              className: "bg-primary w-full overflow-hidden"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
