// Generated by ReScript, PLEASE EDIT WITH CARE

import SendSvg from "./assets/Send.svg";
import StarSvg from "./assets/Star.svg";
import ShieldSvg from "./assets/Shield.svg";
import AirbnbPng from "./assets/airbnb.png";
import BinancePng from "./assets/binance.png";
import DropboxPng from "./assets/dropbox.png";
import TwitterSvg from "./assets/twitter.svg";
import CoinbasePng from "./assets/coinbase.png";
import FacebookSvg from "./assets/facebook.svg";
import LinkedinSvg from "./assets/linkedin.svg";
import People01Jpg from "./assets/people01.jpg";
import People02Jpg from "./assets/people02.jpg";
import People03Jpg from "./assets/people03.jpg";
import InstagramSvg from "./assets/instagram.svg";

var people01 = People01Jpg;

var people02 = People02Jpg;

var people03 = People03Jpg;

var facebook = FacebookSvg;

var instagram = InstagramSvg;

var linkedin = LinkedinSvg;

var twitter = TwitterSvg;

var airbnb = AirbnbPng;

var binance = BinancePng;

var coinbase = CoinbasePng;

var dropbox = DropboxPng;

var send = SendSvg;

var shield = ShieldSvg;

var star = StarSvg;

var navLinks = [
  {
    id: "主页",
    title: "主页",
    link: "#"
  },
  {
    id: "开源",
    title: "开源",
    link: "#opensource"
  },
  {
    id: "作品",
    title: "作品",
    link: "#works"
  },
  {
    id: "社区",
    title: "社区",
    link: "#community"
  }
];

var features = [
  {
    id: "feature-1",
    icon: star,
    title: "共享",
    content: "分享你的开源仓库，或是你认为优秀的开源仓库。与大家一起探索或参与贡献开源世界中的优秀作品。"
  },
  {
    id: "feature-2",
    icon: shield,
    title: "文明",
    content: "在这里我们放下性别、种族、国家和政治立场，仅仅为了相同的热爱而前行。"
  },
  {
    id: "feature-3",
    icon: send,
    title: "交流",
    content: "与社区成员畅谈你的一切，你的生活，你抬头望向的天空，你喜欢的游戏或是任何无关乎违规内容的事物。"
  }
];

var feedback = [
  {
    id: "feedback-1",
    content: "人只不过是一根苇草，是自然界最脆弱的东西，但却是一根能思想的苇草，这个社区让我们的思想交织在了一起。",
    name: "藤椒鱼",
    title: "社区成员 & Web3工程师",
    img: people01
  },
  {
    id: "feedback-2",
    content: "开源项目如同一片广袤的森林，这个社区就像肥沃的土地，每一位贡献者都是其中的一棵树，使我们共同编织出知识与创新的绿荫。",
    name: "执笔人",
    title: "管理员 & 信息安全工程师",
    img: people02
  },
  {
    id: "feedback-3",
    content: "我在这个社区学到了很多新知识，大家分享的资源和经验对我的项目帮助很大，参与开源项目让我感受到了集体智慧的力量，大家一起解决问题的过程非常有成就感。",
    name: "Pu哥",
    title: "社区成员 & 中学生",
    img: people03
  }
];

var stats = [
  {
    id: "stats-1",
    title: "组织成员",
    value: "31 人"
  },
  {
    id: "stats-2",
    title: "开源仓库",
    value: "67 个"
  },
  {
    id: "stats-3",
    title: "社区成员",
    value: "500+ 人"
  }
];

var footerLinks = [
  {
    title: "Useful Links",
    links: [
      {
        name: "Content",
        link: "https://www.hoobank.com/content/"
      },
      {
        name: "How it Works",
        link: "https://www.hoobank.com/how-it-works/"
      },
      {
        name: "Create",
        link: "https://www.hoobank.com/create/"
      },
      {
        name: "Explore",
        link: "https://www.hoobank.com/explore/"
      },
      {
        name: "Terms & Services",
        link: "https://www.hoobank.com/terms-and-services/"
      }
    ]
  },
  {
    title: "Community",
    links: [
      {
        name: "Help Center",
        link: "https://www.hoobank.com/help-center/"
      },
      {
        name: "Partners",
        link: "https://www.hoobank.com/partners/"
      },
      {
        name: "Suggestions",
        link: "https://www.hoobank.com/suggestions/"
      },
      {
        name: "Blog",
        link: "https://www.hoobank.com/blog/"
      },
      {
        name: "Newsletters",
        link: "https://www.hoobank.com/newsletters/"
      }
    ]
  },
  {
    title: "Partner",
    links: [
      {
        name: "Our Partner",
        link: "https://www.hoobank.com/our-partner/"
      },
      {
        name: "Become a Partner",
        link: "https://www.hoobank.com/become-a-partner/"
      }
    ]
  }
];

var socialMedia = [
  {
    id: "social-media-1",
    icon: instagram,
    link: "https://www.instagram.com/"
  },
  {
    id: "social-media-2",
    icon: facebook,
    link: "https://www.facebook.com/"
  },
  {
    id: "social-media-3",
    icon: twitter,
    link: "https://www.twitter.com/"
  },
  {
    id: "social-media-4",
    icon: linkedin,
    link: "https://www.linkedin.com/"
  }
];

var clients = [
  {
    id: "client-1",
    logo: airbnb
  },
  {
    id: "client-2",
    logo: binance
  },
  {
    id: "client-3",
    logo: coinbase
  },
  {
    id: "client-4",
    logo: dropbox
  }
];

export {
  people01 ,
  people02 ,
  people03 ,
  facebook ,
  instagram ,
  linkedin ,
  twitter ,
  airbnb ,
  binance ,
  coinbase ,
  dropbox ,
  send ,
  shield ,
  star ,
  navLinks ,
  features ,
  feedback ,
  stats ,
  footerLinks ,
  socialMedia ,
  clients ,
}
/* people01 Not a pure module */
